"""initial_schema

Revision ID: 1b087c059d7e
Revises: 
Create Date: 2026-04-30 01:59:20.677632+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b087c059d7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_frameworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('compliance_frameworks', schema=None) as batch_op:
        batch_op.create_index('ix_compliance_frameworks_active', ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_frameworks_id'), ['id'], unique=False)

    op.create_table('esg_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pillar', sa.Enum('environmental', 'social', 'governance', name='esg_pillar_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('esg_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esg_categories_id'), ['id'], unique=False)
        batch_op.create_index('ix_esg_categories_pillar', ['pillar'], unique=False)

    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('level', sa.Enum('low', 'medium', 'high', 'critical', name='risk_level_enum'), server_default='medium', nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'mitigated', 'closed', name='risk_status_enum'), server_default='open', nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risks_id'), ['id'], unique=False)
        batch_op.create_index('ix_risks_level', ['level'], unique=False)
        batch_op.create_index('ix_risks_owner', ['owner'], unique=False)
        batch_op.create_index('ix_risks_status', ['status'], unique=False)

    op.create_table('compliance_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('compliant', 'non_compliant', 'partial', 'not_assessed', name='compliance_status_enum'), server_default='not_assessed', nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_requirements', schema=None) as batch_op:
        batch_op.create_index('ix_compliance_requirements_framework_id', ['framework_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_requirements_id'), ['id'], unique=False)
        batch_op.create_index('ix_compliance_requirements_status', ['status'], unique=False)

    op.create_table('esg_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('organisation', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['esg_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('esg_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_esg_metrics_category_id', ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esg_metrics_id'), ['id'], unique=False)
        batch_op.create_index('ix_esg_metrics_organisation', ['organisation'], unique=False)
        batch_op.create_index('ix_esg_metrics_period', ['period'], unique=False)

    op.create_table('esg_score_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False, comment='Best-case value → score 100'),
    sa.Column('baseline_value', sa.Float(), nullable=False, comment='Worst-case value → score 0'),
    sa.Column('direction', sa.Enum('lower_is_better', 'higher_is_better', name='scoring_direction_enum'), server_default='lower_is_better', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['esg_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id')
    )
    with op.batch_alter_table('esg_score_benchmarks', schema=None) as batch_op:
        batch_op.create_index('ix_esg_score_benchmarks_category_id', ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esg_score_benchmarks_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esg_score_benchmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esg_score_benchmarks_id'))
        batch_op.drop_index('ix_esg_score_benchmarks_category_id')

    op.drop_table('esg_score_benchmarks')
    with op.batch_alter_table('esg_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_esg_metrics_period')
        batch_op.drop_index('ix_esg_metrics_organisation')
        batch_op.drop_index(batch_op.f('ix_esg_metrics_id'))
        batch_op.drop_index('ix_esg_metrics_category_id')

    op.drop_table('esg_metrics')
    with op.batch_alter_table('compliance_requirements', schema=None) as batch_op:
        batch_op.drop_index('ix_compliance_requirements_status')
        batch_op.drop_index(batch_op.f('ix_compliance_requirements_id'))
        batch_op.drop_index('ix_compliance_requirements_framework_id')

    op.drop_table('compliance_requirements')
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index('ix_risks_status')
        batch_op.drop_index('ix_risks_owner')
        batch_op.drop_index('ix_risks_level')
        batch_op.drop_index(batch_op.f('ix_risks_id'))

    op.drop_table('risks')
    with op.batch_alter_table('esg_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_esg_categories_pillar')
        batch_op.drop_index(batch_op.f('ix_esg_categories_id'))

    op.drop_table('esg_categories')
    with op.batch_alter_table('compliance_frameworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_frameworks_id'))
        batch_op.drop_index('ix_compliance_frameworks_active')

    op.drop_table('compliance_frameworks')
    # ### end Alembic commands ###
