"""add_per_org_unique_constraints

Revision ID: 07256f6eed55
Revises: e2a54ef84063
Create Date: 2026-05-03 16:45:46.708098+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07256f6eed55'
down_revision: Union[str, None] = 'e2a54ef84063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_frameworks', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_compliance_frameworks_org_name', ['org_id', 'name'])

    with op.batch_alter_table('esg_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_esg_categories_org_name', ['org_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esg_categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_esg_categories_org_name', type_='unique')

    with op.batch_alter_table('compliance_frameworks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_compliance_frameworks_org_name', type_='unique')

    # ### end Alembic commands ###
