"""add_agent_run_logs

Revision ID: 737db0c70862
Revises: 07256f6eed55
Create Date: 2026-05-04 19:03:14.970162+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737db0c70862'
down_revision: Union[str, None] = '07256f6eed55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed', name='agent_run_status_enum'), server_default='running', nullable=False),
    sa.Column('orgs_processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('metrics_scored', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('risks_escalated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('requirements_flagged', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_run_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_logs_id'), ['id'], unique=False)
        batch_op.create_index('ix_agent_run_logs_started_at', ['started_at'], unique=False)
        batch_op.create_index('ix_agent_run_logs_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_run_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_run_logs_status')
        batch_op.drop_index('ix_agent_run_logs_started_at')
        batch_op.drop_index(batch_op.f('ix_agent_run_logs_id'))

    op.drop_table('agent_run_logs')
    # ### end Alembic commands ###
