[theme]
base = "light"
primaryColor = "#CD6752"
backgroundColor = "#F8F6F0"
secondaryBackgroundColor = "#F0EBE1"
textColor = "#162130"
font = "sans serif"

[server]
maxUploadSize = 500

[browser]
gatherUsageStats = false
